// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	example.proto

It has these top-level messages:
	ExampleMessageReq
	InfoMessage
	ExampleMessageRsp
	BytesMessageReq
	BytesMessageRsp
	BytesMessageInfo
	NextMessage
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// protoc -I=protobuf --go_out=protobuf protobuf/*.proto
type ExampleMessageReq struct {
	DocCoolName      *string      `protobuf:"bytes,1,req,name=DocCoolName" json:"DocCoolName,omitempty"`
	Data             *InfoMessage `protobuf:"bytes,2,req,name=Data" json:"Data,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ExampleMessageReq) Reset()                    { *m = ExampleMessageReq{} }
func (m *ExampleMessageReq) String() string            { return proto.CompactTextString(m) }
func (*ExampleMessageReq) ProtoMessage()               {}
func (*ExampleMessageReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ExampleMessageReq) GetDocCoolName() string {
	if m != nil && m.DocCoolName != nil {
		return *m.DocCoolName
	}
	return ""
}

func (m *ExampleMessageReq) GetData() *InfoMessage {
	if m != nil {
		return m.Data
	}
	return nil
}

type InfoMessage struct {
	Method           *string `protobuf:"bytes,1,req,name=Method" json:"Method,omitempty"`
	Url              *string `protobuf:"bytes,2,req,name=Url" json:"Url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *InfoMessage) Reset()                    { *m = InfoMessage{} }
func (m *InfoMessage) String() string            { return proto.CompactTextString(m) }
func (*InfoMessage) ProtoMessage()               {}
func (*InfoMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InfoMessage) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *InfoMessage) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

type ExampleMessageRsp struct {
	DocCoolName      *string      `protobuf:"bytes,1,req,name=DocCoolName" json:"DocCoolName,omitempty"`
	Data             *InfoMessage `protobuf:"bytes,2,req,name=Data" json:"Data,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ExampleMessageRsp) Reset()                    { *m = ExampleMessageRsp{} }
func (m *ExampleMessageRsp) String() string            { return proto.CompactTextString(m) }
func (*ExampleMessageRsp) ProtoMessage()               {}
func (*ExampleMessageRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ExampleMessageRsp) GetDocCoolName() string {
	if m != nil && m.DocCoolName != nil {
		return *m.DocCoolName
	}
	return ""
}

func (m *ExampleMessageRsp) GetData() *InfoMessage {
	if m != nil {
		return m.Data
	}
	return nil
}

type BytesMessageReq struct {
	DocCoolName      *string `protobuf:"bytes,1,req,name=DocCoolName" json:"DocCoolName,omitempty"`
	Data             []byte  `protobuf:"bytes,2,req,name=Data" json:"Data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BytesMessageReq) Reset()                    { *m = BytesMessageReq{} }
func (m *BytesMessageReq) String() string            { return proto.CompactTextString(m) }
func (*BytesMessageReq) ProtoMessage()               {}
func (*BytesMessageReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BytesMessageReq) GetDocCoolName() string {
	if m != nil && m.DocCoolName != nil {
		return *m.DocCoolName
	}
	return ""
}

func (m *BytesMessageReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type BytesMessageRsp struct {
	BytesName        *string `protobuf:"bytes,1,req,name=BytesName" json:"BytesName,omitempty"`
	Data             []byte  `protobuf:"bytes,2,req,name=Data" json:"Data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BytesMessageRsp) Reset()                    { *m = BytesMessageRsp{} }
func (m *BytesMessageRsp) String() string            { return proto.CompactTextString(m) }
func (*BytesMessageRsp) ProtoMessage()               {}
func (*BytesMessageRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BytesMessageRsp) GetBytesName() string {
	if m != nil && m.BytesName != nil {
		return *m.BytesName
	}
	return ""
}

func (m *BytesMessageRsp) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type BytesMessageInfo struct {
	RespName         *string      `protobuf:"bytes,1,req,name=RespName" json:"RespName,omitempty"`
	RespTime         *int64       `protobuf:"varint,2,req,name=RespTime" json:"RespTime,omitempty"`
	Options          *int64       `protobuf:"varint,3,opt,name=Options" json:"Options,omitempty"`
	Data             *NextMessage `protobuf:"bytes,4,req,name=Data" json:"Data,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *BytesMessageInfo) Reset()                    { *m = BytesMessageInfo{} }
func (m *BytesMessageInfo) String() string            { return proto.CompactTextString(m) }
func (*BytesMessageInfo) ProtoMessage()               {}
func (*BytesMessageInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BytesMessageInfo) GetRespName() string {
	if m != nil && m.RespName != nil {
		return *m.RespName
	}
	return ""
}

func (m *BytesMessageInfo) GetRespTime() int64 {
	if m != nil && m.RespTime != nil {
		return *m.RespTime
	}
	return 0
}

func (m *BytesMessageInfo) GetOptions() int64 {
	if m != nil && m.Options != nil {
		return *m.Options
	}
	return 0
}

func (m *BytesMessageInfo) GetData() *NextMessage {
	if m != nil {
		return m.Data
	}
	return nil
}

type NextMessage struct {
	NextName         *string `protobuf:"bytes,1,req,name=NextName" json:"NextName,omitempty"`
	NextTime         *int64  `protobuf:"varint,2,req,name=NextTime" json:"NextTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NextMessage) Reset()                    { *m = NextMessage{} }
func (m *NextMessage) String() string            { return proto.CompactTextString(m) }
func (*NextMessage) ProtoMessage()               {}
func (*NextMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *NextMessage) GetNextName() string {
	if m != nil && m.NextName != nil {
		return *m.NextName
	}
	return ""
}

func (m *NextMessage) GetNextTime() int64 {
	if m != nil && m.NextTime != nil {
		return *m.NextTime
	}
	return 0
}

func init() {
	proto.RegisterType((*ExampleMessageReq)(nil), "protobuf.ExampleMessageReq")
	proto.RegisterType((*InfoMessage)(nil), "protobuf.InfoMessage")
	proto.RegisterType((*ExampleMessageRsp)(nil), "protobuf.ExampleMessageRsp")
	proto.RegisterType((*BytesMessageReq)(nil), "protobuf.BytesMessageReq")
	proto.RegisterType((*BytesMessageRsp)(nil), "protobuf.BytesMessageRsp")
	proto.RegisterType((*BytesMessageInfo)(nil), "protobuf.BytesMessageInfo")
	proto.RegisterType((*NextMessage)(nil), "protobuf.NextMessage")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x69, 0x3b, 0x74, 0x7d, 0x55, 0x9c, 0x0f, 0x94, 0x22, 0x1e, 0xca, 0x4e, 0xf5, 0xd2,
	0x83, 0x17, 0xef, 0x6e, 0x43, 0x3c, 0x6c, 0x42, 0xd0, 0xbb, 0x51, 0xdf, 0x74, 0xd0, 0x2e, 0x71,
	0x89, 0x30, 0x3f, 0x85, 0x5f, 0x59, 0x12, 0x9b, 0xfa, 0x1c, 0xbb, 0x08, 0x3b, 0xb5, 0xbf, 0xff,
	0x0b, 0xbf, 0xfc, 0xf3, 0xe0, 0x90, 0xd6, 0xb2, 0xd1, 0x35, 0x55, 0x7a, 0xa5, 0xac, 0xc2, 0xbe,
	0xff, 0x3c, 0x7d, 0xcc, 0x87, 0x8f, 0x70, 0x3c, 0xf9, 0x19, 0x4d, 0xc9, 0x18, 0xf9, 0x4a, 0x82,
	0xde, 0xb1, 0x80, 0x6c, 0xac, 0x9e, 0x47, 0x4a, 0xd5, 0x33, 0xd9, 0x50, 0x1e, 0x15, 0x71, 0x99,
	0x0a, 0x1e, 0xe1, 0x05, 0xf4, 0xc6, 0xd2, 0xca, 0x3c, 0x2e, 0xe2, 0x32, 0xbb, 0x3c, 0xa9, 0x82,
	0xaf, 0xba, 0x5d, 0xce, 0x55, 0x30, 0xf9, 0x23, 0xc3, 0x2b, 0xc8, 0x58, 0x88, 0xa7, 0xb0, 0x37,
	0x25, 0xfb, 0xa6, 0x5e, 0x5a, 0x6d, 0x4b, 0x38, 0x80, 0xe4, 0x61, 0x55, 0x7b, 0x61, 0x2a, 0xdc,
	0xef, 0x96, 0x6a, 0x46, 0xef, 0xb6, 0xda, 0x0d, 0x1c, 0x5d, 0x7f, 0x5a, 0x32, 0xff, 0x7a, 0x3a,
	0x32, 0xff, 0x41, 0x2b, 0x1a, 0x6d, 0x88, 0x8c, 0xc6, 0x73, 0x48, 0x7d, 0xc4, 0x34, 0xbf, 0xc1,
	0x56, 0xc9, 0x57, 0x04, 0x03, 0x6e, 0x71, 0x7d, 0xf1, 0x0c, 0xfa, 0x82, 0x8c, 0x66, 0x96, 0x8e,
	0xc3, 0xec, 0x7e, 0xd1, 0x90, 0x17, 0x25, 0xa2, 0x63, 0xcc, 0x61, 0xff, 0x4e, 0xdb, 0x85, 0x5a,
	0x9a, 0x3c, 0x29, 0xa2, 0x32, 0x11, 0x01, 0xbb, 0xfd, 0xf4, 0x36, 0xf7, 0x33, 0xa3, 0xb5, 0xfd,
	0xbb, 0x9f, 0x09, 0x64, 0x2c, 0x74, 0xf7, 0x39, 0xe4, 0x5d, 0x02, 0x87, 0x19, 0xef, 0x12, 0xf8,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0x58, 0x6c, 0x99, 0xbc, 0x7d, 0x02, 0x00, 0x00,
}
